"""
magnetic_pendulum_float_fss_annotated.py

Floating-point software reference with Final-State Sensitivity (FSS) analysis.

This script is intended to match the existing floating-point magnetic-pendulum
reference model and add the FSS function that mirrors the proposed hardware
extension.

The important rule is:

    Do not change the pendulum algorithm.

The same simplified force model, semi-implicit Euler update, nearest-magnet
classification, and consecutive settling rule are used for all three runs:

    base   : (x0, y0)
    plus   : (x0 + epsilon, y0)
    minus  : (x0 - epsilon, y0)

The FSS map is then computed as:

    sensitive = (base_label != plus_label) OR (base_label != minus_label)

If any of the three trajectories times out, the pixel is marked as timeout in
the FSS output and is not counted as sensitive. This matches the proposed
hardware format:

    bits [5:2] = base trajectory step category
    bit  [1]   = timeout_any flag
    bit  [0]   = sensitive flag

All parameters are set directly below. No command-line arguments are required.
"""

from pathlib import Path
import json
import time

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.patches import Patch


# =============================================================================
# User-editable parameters
# =============================================================================

WIDTH = 270
HEIGHT = 270

X_MIN = -1.8
X_MAX = 1.8
Y_MIN = -1.8
Y_MAX = 1.8

GAMMA = 0.20
OMEGA2 = 1.00
H2 = 0.25
MU = 1.00

DT = 0.01
MAX_STEPS = 4000
R_SETTLE = 0.25
V_SETTLE = 0.05
MIN_CONSECUTIVE = 3

EPSILON = 0.1
DTYPE = np.float64

CLASSIFY_ON_TIMEOUT = True
PROGRESS_INTERVAL = 500

OUT_DIR = Path("pendulum_outputs_fss_annotated")
SHOW_PLOTS = False

MAGNETS = np.array(
    [
        [1.0, 0.0],
        [-0.5, 0.8660254037844386],
        [-0.5, -0.8660254037844386],
    ],
    dtype=DTYPE,
)

BASIN_COLOURS = {
    0: (220, 60, 60),
    1: (60, 180, 60),
    2: (60, 60, 220),
    -1: (30, 30, 30),
}


# =============================================================================
# Grid and physics functions
# =============================================================================


def build_initial_grid(x_offset=0.0):
    """
    Build the initial-condition grid.

    Each image pixel represents one initial position (x0, y0). For FSS, the
    plus and minus runs are generated by adding an x_offset to the base grid.

    x_offset = 0.0      gives (x0, y0)
    x_offset = epsilon  gives (x0 + epsilon, y0)
    x_offset = -epsilon gives (x0 - epsilon, y0)

    No clipping is applied. If x0 + epsilon lies slightly outside the displayed
    physical window, it is still simulated as a valid perturbed coordinate.
    """

    xs = np.linspace(X_MIN, X_MAX, WIDTH, dtype=DTYPE) + DTYPE(x_offset)
    ys = np.linspace(Y_MIN, Y_MAX, HEIGHT, dtype=DTYPE)
    x, y = np.meshgrid(xs, ys, indexing="xy")
    return x, y


def acceleration(x, y, vx, vy):
    """
    Compute acceleration for the simplified magnetic-pendulum model.

    This is the same force model as the floating-point reference:

        ax = -gamma * vx - omega2 * x
             + mu * sum_i dx_i * q_i^(-3/2)

        ay = -gamma * vy - omega2 * y
             + mu * sum_i dy_i * q_i^(-3/2)

    where:

        dx_i = magnet_x_i - x
        dy_i = magnet_y_i - y
        q_i  = dx_i^2 + dy_i^2 + h2

    The q^(-3/2) term is the expensive term approximated by a LUT in hardware.
    """

    ax = -GAMMA * vx - OMEGA2 * x
    ay = -GAMMA * vy - OMEGA2 * y

    for mx, my in MAGNETS:
        dx = mx - x
        dy = my - y
        q = dx * dx + dy * dy + H2
        inv_q_3_2 = q ** (-1.5)
        ax = ax + MU * dx * inv_q_3_2
        ay = ay + MU * dy * inv_q_3_2

    return ax, ay


def nearest_magnet(x, y):
    """
    Return the nearest magnet ID and squared planar distance.

    The squared distance is used because only comparisons are needed. This is
    the same idea used in hardware to avoid a square-root operation.
    """

    distances = []

    for mx, my in MAGNETS:
        dx = mx - x
        dy = my - y
        distances.append(dx * dx + dy * dy)

    d2_stack = np.stack(distances, axis=0)
    label = np.argmin(d2_stack, axis=0).astype(np.int16)
    d2_min = np.min(d2_stack, axis=0)
    return label, d2_min


def step_category_from_steps(steps, timeout_mask):
    """
    Convert raw step counts into the same 4-bit step category used in hardware.

    Category 0 is reserved for timeout. Categories 1 to 11 represent increasing
    settling time ranges.
    """

    cat = np.zeros_like(steps, dtype=np.uint8)

    cat[(~timeout_mask) & (steps <= 500)] = 1
    cat[(~timeout_mask) & (steps > 500) & (steps <= 1000)] = 2
    cat[(~timeout_mask) & (steps > 1000) & (steps <= 1500)] = 3
    cat[(~timeout_mask) & (steps > 1500) & (steps <= 2000)] = 4
    cat[(~timeout_mask) & (steps > 2000) & (steps <= 2500)] = 5
    cat[(~timeout_mask) & (steps > 2500) & (steps <= 3000)] = 6
    cat[(~timeout_mask) & (steps > 3000) & (steps <= 3500)] = 7
    cat[(~timeout_mask) & (steps > 3500) & (steps <= 4000)] = 8
    cat[(~timeout_mask) & (steps > 4000) & (steps <= 4500)] = 9
    cat[(~timeout_mask) & (steps > 4500) & (steps <= 5000)] = 10
    cat[(~timeout_mask) & (steps > 5000)] = 11

    return cat


# =============================================================================
# Basin simulation
# =============================================================================


def generate_basin_map(x_offset=0.0, name="base"):
    """
    Generate one basin map for a given x-offset.

    This function is used three times for FSS:

        x_offset = 0.0       base trajectory
        x_offset = EPSILON   positive perturbation
        x_offset = -EPSILON  negative perturbation

    The algorithm is intentionally unchanged between the three runs. Only the
    initial x-coordinate is shifted.
    """

    x, y = build_initial_grid(x_offset=x_offset)
    vx = np.zeros_like(x)
    vy = np.zeros_like(y)

    basin = np.full((HEIGHT, WIDTH), -1, dtype=np.int16)
    steps = np.zeros((HEIGHT, WIDTH), dtype=np.int32)
    strictly_settled = np.zeros((HEIGHT, WIDTH), dtype=bool)
    active = np.ones((HEIGHT, WIDTH), dtype=bool)
    consecutive = np.zeros((HEIGHT, WIDTH), dtype=np.int16)

    r2_settle = R_SETTLE * R_SETTLE
    v2_settle = V_SETTLE * V_SETTLE

    t0 = time.perf_counter()
    last_step = 0

    for step in range(1, MAX_STEPS + 1):
        last_step = step

        ax, ay = acceleration(x, y, vx, vy)

        vx[active] = vx[active] + DT * ax[active]
        vy[active] = vy[active] + DT * ay[active]
        x[active] = x[active] + DT * vx[active]
        y[active] = y[active] + DT * vy[active]

        label, d2_min = nearest_magnet(x, y)
        speed2 = vx * vx + vy * vy

        settle_now = active & (d2_min < r2_settle) & (speed2 < v2_settle)
        consecutive[settle_now] += 1
        consecutive[active & ~settle_now] = 0

        done_now = active & (consecutive >= MIN_CONSECUTIVE)

        if np.any(done_now):
            basin[done_now] = label[done_now]
            steps[done_now] = step
            strictly_settled[done_now] = True
            active[done_now] = False

        if PROGRESS_INTERVAL > 0:
            should_print = (
                step == 1
                or step % PROGRESS_INTERVAL == 0
                or step == MAX_STEPS
                or not np.any(active)
            )
            if should_print:
                done_count = int(np.size(active) - np.sum(active))
                print(
                    f"{name:>6s} | step {step:5d}/{MAX_STEPS} | "
                    f"done {done_count:7d}/{WIDTH * HEIGHT}"
                )

        if not np.any(active):
            break

    if np.any(active):
        label, _ = nearest_magnet(x, y)
        if CLASSIFY_ON_TIMEOUT:
            basin[active] = label[active]
        else:
            basin[active] = -1
        steps[active] = MAX_STEPS

    elapsed_s = time.perf_counter() - t0

    return {
        "basin": basin,
        "steps": steps,
        "strictly_settled": strictly_settled,
        "timeout": ~strictly_settled,
        "elapsed_s": elapsed_s,
        "iterations_executed": last_step,
        "final_x": x,
        "final_y": y,
        "final_vx": vx,
        "final_vy": vy,
    }


# =============================================================================
# FSS computation
# =============================================================================


def compute_fss(base, plus, minus):
    """
    Compute the FSS map from three basin maps.

    A pixel is sensitive only if:

        1. none of the three trajectories timed out, and
        2. the final magnet of the plus or minus perturbation differs from base.

    timeout_any is stored separately because timeout means the FSS decision is
    not reliable for that pixel.
    """

    base_label = base["basin"]
    plus_label = plus["basin"]
    minus_label = minus["basin"]

    timeout_any = base["timeout"] | plus["timeout"] | minus["timeout"]

    sensitive = (
        (~timeout_any)
        & ((base_label != plus_label) | (base_label != minus_label))
    )

    base_step_cat = step_category_from_steps(base["steps"], base["timeout"])

    fss_word = (
        (base_step_cat.astype(np.uint8) << 2)
        | (timeout_any.astype(np.uint8) << 1)
        | sensitive.astype(np.uint8)
    )

    return {
        "sensitive": sensitive,
        "timeout_any": timeout_any,
        "base_step_category": base_step_cat,
        "fss_word": fss_word,
        "sensitive_count": int(np.sum(sensitive)),
        "timeout_count": int(np.sum(timeout_any)),
        "f_epsilon": float(np.mean(sensitive)),
        "timeout_fraction": float(np.mean(timeout_any)),
    }


# =============================================================================
# Plotting helpers
# =============================================================================


def basin_to_rgb(basin, timeout_mask=None, darken_timeout=False):
    """
    Convert integer basin labels into RGB colours.

    timeout pixels can optionally be darkened. The numerical arrays always keep
    timeout information separately, so this is only a visual choice.
    """

    rgb = np.zeros((basin.shape[0], basin.shape[1], 3), dtype=np.uint8)

    for label, colour in BASIN_COLOURS.items():
        rgb[basin == label] = np.array(colour, dtype=np.uint8)

    if darken_timeout and timeout_mask is not None:
        rgb[timeout_mask] = (0.45 * rgb[timeout_mask]).astype(np.uint8)

    return rgb


def save_annotated_basin(base, path):
    """
    Save an annotated basin-of-attraction plot.

    The output includes:
        - physical x/y axes,
        - magnet markers,
        - a colour legend,
        - a title with the main simulation parameters.
    """

    rgb = basin_to_rgb(base["basin"], base["timeout"], darken_timeout=False)

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.imshow(
        rgb,
        origin="lower",
        extent=[X_MIN, X_MAX, Y_MIN, Y_MAX],
        interpolation="nearest",
    )

    for i, (mx, my) in enumerate(MAGNETS):
        ax.plot(mx, my, marker="+", color="white", markersize=14, markeredgewidth=2.5)
        ax.text(mx + 0.06, my + 0.06, f"M{i}", color="white", fontsize=11, weight="bold")

    legend_items = [
        Patch(facecolor=np.array(BASIN_COLOURS[0]) / 255.0, label="Magnet 0"),
        Patch(facecolor=np.array(BASIN_COLOURS[1]) / 255.0, label="Magnet 1"),
        Patch(facecolor=np.array(BASIN_COLOURS[2]) / 255.0, label="Magnet 2"),
    ]

    ax.legend(handles=legend_items, loc="upper right", framealpha=0.85)
    ax.set_title(
        "Basin of Attraction Map\n"
        f"resolution={WIDTH}x{HEIGHT}, gamma={GAMMA}, dt={DT}, max_steps={MAX_STEPS}"
    )
    ax.set_xlabel("initial x position, $x_0$")
    ax.set_ylabel("initial y position, $y_0$")

    timeout_count = int(np.sum(base["timeout"]))
    settled_percent = 100.0 * float(np.mean(base["strictly_settled"]))
    text = (
        f"strictly settled: {settled_percent:.2f}%\n"
        f"timeout-classified pixels: {timeout_count}"
    )
    ax.text(
        0.02,
        0.02,
        text,
        transform=ax.transAxes,
        color="white",
        fontsize=10,
        bbox=dict(facecolor="black", alpha=0.55, edgecolor="none"),
    )

    fig.tight_layout()
    fig.savefig(path, dpi=220, bbox_inches="tight")
    if SHOW_PLOTS:
        plt.show()
    plt.close(fig)


def save_annotated_fss_map(fss, path):
    """
    Save an annotated FSS map.

    Value convention for the displayed image:
        0 = stable
        1 = sensitive
        2 = timeout/invalid for FSS

    The saved numerical file fss_sensitive.npy stores only the Boolean sensitive
    map. The saved fss_timeout_any.npy stores timeout information separately.
    """

    display = np.zeros((HEIGHT, WIDTH), dtype=np.uint8)
    display[fss["sensitive"]] = 1
    display[fss["timeout_any"]] = 2

    cmap = ListedColormap(
        [
            (0.08, 0.10, 0.16),
            (1.00, 0.75, 0.12),
            (0.45, 0.45, 0.45),
        ]
    )

    fig, ax = plt.subplots(figsize=(8, 7))
    ax.imshow(
        display,
        origin="lower",
        extent=[X_MIN, X_MAX, Y_MIN, Y_MAX],
        interpolation="nearest",
        cmap=cmap,
        vmin=0,
        vmax=2,
    )

    for i, (mx, my) in enumerate(MAGNETS):
        ax.plot(mx, my, marker="+", color="white", markersize=14, markeredgewidth=2.5)
        ax.text(mx + 0.06, my + 0.06, f"M{i}", color="white", fontsize=11, weight="bold")

    legend_items = [
        Patch(facecolor=(0.08, 0.10, 0.16), label="Stable"),
        Patch(facecolor=(1.00, 0.75, 0.12), label="Sensitive"),
        Patch(facecolor=(0.45, 0.45, 0.45), label="Timeout / invalid"),
    ]

    ax.legend(handles=legend_items, loc="upper right", framealpha=0.85)
    ax.set_title(
        "Final-State Sensitivity Map\n"
        f"epsilon={EPSILON}, sensitive fraction={100.0 * fss['f_epsilon']:.2f}%"
    )
    ax.set_xlabel("initial x position, $x_0$")
    ax.set_ylabel("initial y position, $y_0$")

    text = (
        f"sensitive pixels: {fss['sensitive_count']} / {WIDTH * HEIGHT}\n"
        f"timeout/invalid pixels: {fss['timeout_count']}\n"
        "test: compare $A(x_0,y_0)$ with "
        "$A(x_0+\\epsilon,y_0)$ and $A(x_0-\\epsilon,y_0)$"
    )
    ax.text(
        0.02,
        0.02,
        text,
        transform=ax.transAxes,
        color="white",
        fontsize=10,
        bbox=dict(facecolor="black", alpha=0.60, edgecolor="none"),
    )

    fig.tight_layout()
    fig.savefig(path, dpi=220, bbox_inches="tight")
    if SHOW_PLOTS:
        plt.show()
    plt.close(fig)


def save_step_heatmap(base, path):
    """Save an annotated heatmap of the base trajectory step count."""

    fig, ax = plt.subplots(figsize=(8, 7))
    im = ax.imshow(
        base["steps"],
        origin="lower",
        extent=[X_MIN, X_MAX, Y_MIN, Y_MAX],
        interpolation="nearest",
        cmap="inferno",
    )

    for i, (mx, my) in enumerate(MAGNETS):
        ax.plot(mx, my, marker="+", color="white", markersize=12, markeredgewidth=2)
        ax.text(mx + 0.06, my + 0.06, f"M{i}", color="white", fontsize=10, weight="bold")

    fig.colorbar(im, ax=ax, label="integration steps")
    ax.set_title("Base Trajectory Step Count Heatmap")
    ax.set_xlabel("initial x position, $x_0$")
    ax.set_ylabel("initial y position, $y_0$")
    fig.tight_layout()
    fig.savefig(path, dpi=220, bbox_inches="tight")
    if SHOW_PLOTS:
        plt.show()
    plt.close(fig)


# =============================================================================
# Saving numerical outputs
# =============================================================================


def save_arrays(base, plus, minus, fss):
    """Save all arrays needed for hardware/software comparison."""

    np.save(OUT_DIR / "basin_base.npy", base["basin"])
    np.save(OUT_DIR / "basin_plus_epsilon.npy", plus["basin"])
    np.save(OUT_DIR / "basin_minus_epsilon.npy", minus["basin"])

    np.save(OUT_DIR / "steps_base.npy", base["steps"])
    np.save(OUT_DIR / "steps_plus_epsilon.npy", plus["steps"])
    np.save(OUT_DIR / "steps_minus_epsilon.npy", minus["steps"])

    np.save(OUT_DIR / "strictly_settled_base.npy", base["strictly_settled"])
    np.save(OUT_DIR / "strictly_settled_plus_epsilon.npy", plus["strictly_settled"])
    np.save(OUT_DIR / "strictly_settled_minus_epsilon.npy", minus["strictly_settled"])

    np.save(OUT_DIR / "fss_sensitive.npy", fss["sensitive"])
    np.save(OUT_DIR / "fss_timeout_any.npy", fss["timeout_any"])
    np.save(OUT_DIR / "fss_base_step_category.npy", fss["base_step_category"])
    np.save(OUT_DIR / "fss_word.npy", fss["fss_word"])

    np.savez_compressed(
        OUT_DIR / "fss_result_bundle.npz",
        basin_base=base["basin"],
        basin_plus=plus["basin"],
        basin_minus=minus["basin"],
        steps_base=base["steps"],
        fss_sensitive=fss["sensitive"],
        fss_timeout_any=fss["timeout_any"],
        fss_word=fss["fss_word"],
    )


def save_summary(base, plus, minus, fss):
    """Save a JSON summary of parameters and FSS statistics."""

    summary = {
        "resolution": [WIDTH, HEIGHT],
        "window": {
            "x_min": X_MIN,
            "x_max": X_MAX,
            "y_min": Y_MIN,
            "y_max": Y_MAX,
        },
        "physics": {
            "gamma": GAMMA,
            "omega2": OMEGA2,
            "h2": H2,
            "mu": MU,
        },
        "simulation": {
            "dt": DT,
            "max_steps": MAX_STEPS,
            "r_settle": R_SETTLE,
            "v_settle": V_SETTLE,
            "min_consecutive": MIN_CONSECUTIVE,
            "classify_on_timeout": CLASSIFY_ON_TIMEOUT,
        },
        "fss": {
            "epsilon": EPSILON,
            "definition": "sensitive = no_timeout and ((base != plus) or (base != minus))",
            "sensitive_count": fss["sensitive_count"],
            "sensitive_fraction": fss["f_epsilon"],
            "sensitive_percent": 100.0 * fss["f_epsilon"],
            "timeout_count": fss["timeout_count"],
            "timeout_fraction": fss["timeout_fraction"],
            "hardware_word_format": {
                "bits_5_2": "base trajectory step category",
                "bit_1": "timeout_any flag",
                "bit_0": "sensitive flag",
            },
        },
        "runtime_seconds": {
            "base": base["elapsed_s"],
            "plus_epsilon": plus["elapsed_s"],
            "minus_epsilon": minus["elapsed_s"],
            "total": base["elapsed_s"] + plus["elapsed_s"] + minus["elapsed_s"],
        },
    }

    with open(OUT_DIR / "summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)


# =============================================================================
# Main run
# =============================================================================


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Magnetic pendulum floating-point FSS reference")
    print("------------------------------------------------")
    print(f"resolution : {WIDTH} x {HEIGHT}")
    print(f"epsilon    : {EPSILON}")
    print(f"gamma      : {GAMMA}")
    print(f"output dir : {OUT_DIR.resolve()}")

    print("\nGenerating base basin map...")
    base = generate_basin_map(x_offset=0.0, name="base")

    print("\nGenerating plus-epsilon basin map...")
    plus = generate_basin_map(x_offset=EPSILON, name="plus")

    print("\nGenerating minus-epsilon basin map...")
    minus = generate_basin_map(x_offset=-EPSILON, name="minus")

    print("\nComputing FSS map...")
    fss = compute_fss(base, plus, minus)

    print("\nSaving arrays and plots...")
    save_arrays(base, plus, minus, fss)
    save_summary(base, plus, minus, fss)

    plt.imsave(OUT_DIR / "basin_base_raw.png", basin_to_rgb(base["basin"]))
    save_annotated_basin(base, OUT_DIR / "basin_base_annotated.png")
    save_annotated_fss_map(fss, OUT_DIR / "fss_map_annotated.png")
    save_step_heatmap(base, OUT_DIR / "step_base_annotated.png")

    print("\nFSS summary:")
    print(f"  sensitive pixels : {fss['sensitive_count']} / {WIDTH * HEIGHT}")
    print(f"  f_epsilon        : {fss['f_epsilon']:.6f}")
    print(f"  sensitive percent: {100.0 * fss['f_epsilon']:.2f}%")
    print(f"  timeout pixels   : {fss['timeout_count']} / {WIDTH * HEIGHT}")
    print("\nSaved files:")
    print(f"  {OUT_DIR / 'basin_base_annotated.png'}")
    print(f"  {OUT_DIR / 'fss_map_annotated.png'}")
    print(f"  {OUT_DIR / 'step_base_annotated.png'}")
    print(f"  {OUT_DIR / 'summary.json'}")


if __name__ == "__main__":
    main()
